---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
    - secretKey: superuser_name
      remoteRef:
        key: secret/linkding
        property: superuser_name
    - secretKey: superuser_password
      remoteRef:
        key: secret/linkding
        property: superuser_password
